### ISSUE TITLE
[SUGGESTION] Single line start message

### ISSUE THREAD

**Issue by srnyx** [wafflecoffee/clean-logs#3]
Can you add a message that will be sent when the mod fully loads? This will allow me to know which phrases I can put into the config that will actually be filtered out (as messages before the mod loads won't be filtered).

**Comment by wafflecoffee** [comment]
This is enabled by default with the `printOnStart` option in `clean-logs.toml`.

**Comment by srnyx** [comment]
> This is enabled by default with the `printOnStart` option in `clean-logs.toml`.

Doesn't that send every single defined filter though?

**Comment by wafflecoffee** [comment]
It does... should I make a separate option for just that line, then?
For what it's worth, it loads pretty early, just not as early as the mixins or some other mods. This is because Clean Logs uses the prelaunch entrypoint, so it will always start before most mods.
![image](https://user-images.githubusercontent.com/60205699/148658284-d3b35a3e-f133-4f34-9ccf-e3161648408b.png)

**Comment by srnyx** [comment]
> It does... should I make a separate option for just that line, then?

Yeah, a separate option for just sending 1 line would be great.

**Comment by wafflecoffee** [comment]
https://modrinth.com/mod/clean-logs/version/kTF3wEQF
